topics:
-
  name    : move_base
  topic   : move_base/cmd_vel
  timeout : 0.5
  priority: 10
-
  name    : sonar_obstacle_avoidance
  topic   : sonar/cmd_vel
  timeout : 0.5
  priority: 50
-
  name    : joysticks
  topic   : joy/cmd_vel
  timeout : 0.5
  priority: 100

locks:
-
  name    : pause
  topic   : pause_navigation
  timeout : 0.0
  # Same priority as joystick control, so it'll not block it.
  priority: 100
-
  name    : joystick 
  topic   : joy_priority
  timeout : 0.0
  priority: 100